### ISSUE TITLE
The npm start stuck!

### ISSUE THREAD

**Issue by ruCyberPoison** [UnicornTranscoder/UnicornLoadBalancer#17]
Hi,

I have some issues with the UnicornLoadBalancer because he still stuck on 
> unicorn-load-balancer@2.0.0 start /root/UnicornLoadBalancer
> node index.js

This is normal ? 

How can i test in local (without clustering) the streams ? 
When i change the binary he don't transcode anymore

**Comment by Maxou44** [comment]
What is your node version ?
Did you `npm i` ?
Did you enable log with the env DEBUG=* ?

**Comment by ruCyberPoison** [comment]
Now i get this issue 

```
Error: listen EADDRINUSE :::3001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/root/UnicornLoadBalancer/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/UnicornLoadBalancer/src/app.js:57:24)
    at Generator.next (<anonymous>)
```

**Comment by Maxou44** [comment]
The server is already running

**Comment by ruCyberPoison** [comment]
Oh nice i found now how to start it properbly. 

In your notes you write to remove Plex Relay binary, where can i found it ? 
and where is the location of the transcoder binary ? 

I thinks this is important to add in your tutorial maybe can help people to find the locations more easely

**Comment by Maxou44** [comment]
The binary to use instead of the transcoder >> https://github.com/UnicornTranscoder/UnicornFFMPEG
Plex Relay binary can be found in Plex files
Documentation is clear, just read it 😁
